{
 "title": "Node Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (%): $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$node\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Used"
    }
   ]
  },
  {
   "title": "Memory Usage (%): $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"}))",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Average Disk I/O Latency: $node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1000 * sum by (device) (rate(node_disk_read_time_seconds_total{instance=\"$node\"}[1m])) / sum by (device) (rate(node_disk_reads_completed_total{instance=\"$node\"}[1m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization (%): $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "Disk: {{device}}",
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$node\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "Disk Read/Write Throughput: $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "legendFormat": "Disk read",
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$node\"}[1m])) by (device)"
    },
    {
     "legendFormat": "Disk write",
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$node\"}[1m])) by (device)"
    }
   ]
  },
  {
   "title": "Disk Used (%): $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "{{label_name}}",
     "expr": "(sum(node_filesystem_size_bytes{instance=\"$node\", fstype!~\"tmpfs|overlay\"}) - sum(node_filesystem_free_bytes{instance=\"$node\", fstype!~\"tmpfs|overlay\"})) / sum(node_filesystem_size_bytes{instance=\"$node\", fstype!~\"tmpfs|overlay\"}) * 100"
    }
   ]
  },
  {
   "title": "Network RX (MB/s): $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\"}[1m])",
     "legendFormat": "Device: {{device}}"
    }
   ]
  },
  {
   "title": "Network TX (MB/s): $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\"}[1m])",
     "legendFormat": "Device: {{device}}"
    }
   ]
  }
 ]
}